name: 'Clone Repositories'
description: 'Clone self and upstream repositories'
runs:
  using: 'composite'
  steps:
    - name: Output rolldown and rolldown-vite hash
      shell: bash
      id: upstream-versions
      run: |
        node -e "console.log('ROLLDOWN_HASH=' + require('./packages/tools/.upstream-versions.json').rolldown.hash)" >> $GITHUB_OUTPUT
        node -e "console.log('ROLLDOWN_VITE_HASH=' + require('./packages/tools/.upstream-versions.json')['rolldown-vite'].hash)" >> $GITHUB_OUTPUT

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: rolldown/rolldown
        path: rolldown
        ref: ${{ steps.upstream-versions.outputs.ROLLDOWN_HASH }}

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: vitejs/rolldown-vite
        path: rolldown-vite
        ref: ${{ steps.upstream-versions.outputs.ROLLDOWN_VITE_HASH }}
