// Release builds rewrite bundled Rolldown's native binding requires from
// `@rolldown/binding-<platform>` to the Vite+ platform packages
// (`@voidzero-dev/vite-plus-<platform>`), whose merged `.node` contains
// `rolldown_binding`. Core declares those packages as `optionalDependencies`
// at publish time (see packages/cli/publish-native-addons.ts), so the bundled
// loader resolves through declared dependencies instead of requiring back into
// `vite-plus`. See rfcs/core-binding-resolution.md.

export interface RewriteRolldownBindingOptions {
  /**
   * napi platform suffixes Vite+ ships native packages for, e.g.
   * `darwin-arm64`, `linux-x64-musl` (derived from the CLI's `napi.targets`).
   * Specifiers for other platforms, including the `wasm32-wasi` fallback,
   * are left on `@rolldown/binding-*` and keep their upstream version guards.
   */
  platformSuffixes: ReadonlySet<string>;
  /** Version the platform packages are published as (core's own version). */
  version: string;
}

export interface RewriteRolldownBindingResult {
  source: string;
  /** `@rolldown/binding-<suffix>` occurrences rewritten (two per branch). */
  specifierRewrites: number;
  /** Version guards rewritten (one per branch). */
  guardRewrites: number;
}

const SPECIFIER_RE = /@rolldown\/binding-([a-z0-9-]+)/g;

// A rewritten platform branch's version guard, generated by napi-rs:
//
//   const bindingPackageVersion = __require("@voidzero-dev/vite-plus-<suffix>/package.json").version;
//   if (bindingPackageVersion !== "<rolldown version>" && ...) throw new Error(`... expected <rolldown version> but got ...`);
//
// Anchoring on the rewritten specifier scopes the version replacement to
// branches this build actually redirects; guards of platforms left on
// `@rolldown/binding-*` keep comparing against the Rolldown version.
const GUARD_RE =
  /(__require\((["'])@voidzero-dev\/vite-plus-[a-z0-9-]+\/package\.json\2\)\.version;\s*if \(bindingPackageVersion !== )(["'])[^"']+\3([\s\S]{0,400}?expected )\S+( but got)/g;

export function rewriteRolldownBindingRequires(
  source: string,
  { platformSuffixes, version }: RewriteRolldownBindingOptions,
): RewriteRolldownBindingResult {
  let specifierRewrites = 0;
  let rewritten = source.replace(SPECIFIER_RE, (specifier, suffix: string) => {
    if (!platformSuffixes.has(suffix)) {
      return specifier;
    }
    specifierRewrites += 1;
    return `@voidzero-dev/vite-plus-${suffix}`;
  });

  let guardRewrites = 0;
  rewritten = rewritten.replace(
    GUARD_RE,
    (_match, head: string, _specifierQuote, versionQuote: string, mid: string, tail: string) => {
      guardRewrites += 1;
      return `${head}${versionQuote}${version}${versionQuote}${mid}${version}${tail}`;
    },
  );

  return { source: rewritten, specifierRewrites, guardRewrites };
}
