name: 'Build with Upstream Repositories'
description: 'Builds Vite+ with the upstream repositories'
inputs:
  target:
    description: 'The target platform'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/download-rolldown-binaries
      with:
        github-token: ${{ github.token }}
        target: ${{ inputs.target }}
        upload: 'false'
    - name: Patch Vite
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          sed -i '' '123,124d' rolldown-vite/packages/vite/rolldown.dts.config.ts
        else
          sed -i '123,124d' rolldown-vite/packages/vite/rolldown.dts.config.ts
        fi

    - name: Build
      shell: bash
      if: ${{ inputs.target == 'x86_64-unknown-linux-gnu' }}
      run: |
        pnpm --filter @rolldown/pluginutils build
        pnpm --filter rolldown build-node
        pnpm --filter vite build-types
        pnpm --filter=@voidzero-dev/vite-plus-core build
        pnpm --filter=@voidzero-dev/vite-plus-test build
        pnpm --filter=vite-plus build --target ${{ inputs.target }} --use-napi-cross
        pnpm --filter=vite-plus-cli build --target ${{ inputs.target }} --use-napi-cross
      env:
        TARGET_CC: clang
        DEBUG: napi:*

    - name: Build
      shell: bash
      if: ${{ inputs.target == 'aarch64-unknown-linux-gnu' }}
      run: |
        pnpm --filter @rolldown/pluginutils build
        pnpm --filter rolldown build-node
        pnpm --filter vite build-types
        pnpm --filter=@voidzero-dev/vite-plus-core build
        pnpm --filter=@voidzero-dev/vite-plus-test build
        TARGET_CFLAGS="-D_BSD_SOURCE" pnpm --filter=vite-plus build --target ${{ inputs.target }} --use-napi-cross
        TARGET_CFLAGS="-D_BSD_SOURCE" pnpm --filter=vite-plus-cli build --target ${{ inputs.target }} --use-napi-cross
      env:
        TARGET_CC: clang
        DEBUG: napi:*

    - name: Build
      shell: bash
      if: ${{ !contains(inputs.target, 'linux') }}
      run: |
        pnpm --filter @rolldown/pluginutils build
        pnpm --filter rolldown build-node
        pnpm --filter vite build-types
        pnpm --filter=@voidzero-dev/vite-plus-core build
        pnpm --filter=@voidzero-dev/vite-plus-test build
        pnpm --filter=vite-plus build --target ${{ inputs.target }}
        pnpm --filter=vite-plus-cli build --target ${{ inputs.target }}
      env:
        DEBUG: napi:*
