[package]
name = "vp_cli_help"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[features]
default = ["clap"]
clap = ["dep:clap"]
usage = ["dep:usage-rs"]

[dependencies]
clap = { workspace = true, optional = true }
owo-colors = { workspace = true }
terminal_size = { workspace = true }
usage-rs = { workspace = true, optional = true }
vp_shared = { workspace = true }

[lints]
workspace = true
