[package]
name = "foo"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "vite"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
crossterm = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
