/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Configuration options passed from JavaScript to Rust. */
export interface CliOptions {
  lint: (err: Error | null) => Promise<JsCommandResolvedResult>;
  fmt: (err: Error | null) => Promise<JsCommandResolvedResult>;
  vite: (err: Error | null) => Promise<JsCommandResolvedResult>;
  test: (err: Error | null) => Promise<JsCommandResolvedResult>;
  lib: (err: Error | null) => Promise<JsCommandResolvedResult>;
  doc: (err: Error | null) => Promise<JsCommandResolvedResult>;
  cwd?: string;
  /** CLI arguments (should be process.argv.slice(2) from JavaScript) */
  args?: Array<string>;
  /** Read the vite.config.ts in the Node.js side and return the `lint` and `fmt` config JSON string back to the Rust side */
  resolveUniversalViteConfig: (err: Error | null, arg: string) => Promise<string>;
}

/** Result returned by JavaScript resolver functions. */
export interface JsCommandResolvedResult {
  binPath: string;
  envs: Record<string, string>;
}

/**
 * Main entry point for the CLI, called from JavaScript.
 *
 * This is an async function that spawns a new thread for the non-Send async code
 * from vite_task, while allowing the NAPI async context to continue running
 * and process JavaScript callbacks (via ThreadsafeFunction).
 */
export declare function run(options: CliOptions): Promise<number>;
