/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CliOptions {
  lint: ((err: Error | null, ) => Promise<JsCommandResolvedResult>)
  cwd?: string
}

export interface JsCommandResolvedResult {
  binPath: string
  envs: Record<string, string>
}

export declare function run(options: CliOptions): Promise<void>
