[build]
rustflags = ["--cfg", "tokio_unstable"] # also update .github/workflows/ci.yml
# fix sqlite build error on linux
[target.'cfg(target_os = "linux")']
rustflags = [
  "--cfg",
  "tokio_unstable",
  "-C",
  "link-args=-Wl,--warn-unresolved-symbols",
]

[unstable]
bindeps = true

[net]
git-fetch-with-cli = true #  use git CLI to authenticate for vite-task git dependencies
