export * from '@voidzero-dev/vite-plus/test';
export {
  type Alias,
  type AliasOptions,
  type AnymatchFn,
  type AnymatchPattern,
  type AppType,
  type BindCLIShortcutsOptions,
  build,
  type BuildAppHook,
  BuildEnvironment,
  type BuildEnvironmentOptions,
  type BuilderOptions,
  buildErrorMessage,
  type BuildOptions,
  type ChunkMetadata,
  type CLIShortcut,
  type CommonServerOptions,
  type ConfigEnv,
  type ConfigPluginContext,
  type Connect,
  type ConnectedPayload,
  type CorsOptions,
  type CorsOrigin,
  createBuilder,
  createFetchableDevEnvironment,
  createFilter,
  createIdResolver,
  createLogger,
  createRunnableDevEnvironment,
  createServer,
  createServerHotChannel,
  createServerModuleRunner,
  createServerModuleRunnerTransport,
  type CSSModulesOptions,
  type CSSOptions,
  type CustomEventMap,
  type CustomPayload,
  type CustomPluginOptionsVite,
  defaultAllowedOrigins,
  defaultClientConditions,
  defaultClientMainFields,
  defaultExternalConditions,
  defaultServerConditions,
  defaultServerMainFields,
  type DepOptimizationConfig,
  type DepOptimizationMetadata,
  type DepOptimizationOptions,
  DevEnvironment,
  type DevEnvironmentContext,
  type DevEnvironmentOptions,
  type Environment,
  type EnvironmentModuleGraph,
  type EnvironmentModuleNode,
  type EnvironmentOptions,
  type ErrorPayload,
  type ESBuildOptions,
  type EsbuildTransformOptions,
  esbuildVersion,
  esmExternalRequirePlugin,
  type ExperimentalOptions,
  type ExportsData,
  type FetchableDevEnvironment,
  type FetchableDevEnvironmentContext,
  type FetchFunction,
  fetchModule,
  type FetchModuleOptions,
  type FetchResult,
  type FileSystemServeOptions,
  type FilterPattern,
  formatPostcssSourceMap,
  type FSWatcher,
  type FullReloadPayload,
  type GeneralImportGlobOptions,
  type HmrContext,
  type HmrOptions,
  type HMRPayload,
  type HookHandler,
  type HotChannel,
  type HotChannelClient,
  type HotChannelListener,
  type HotPayload,
  type HotUpdateOptions,
  type HTMLOptions,
  type HtmlTagDescriptor,
  type HttpProxy,
  type HttpServer,
  type ImportGlobFunction,
  type ImportGlobOptions,
  type IndexHtmlTransform,
  type IndexHtmlTransformContext,
  type IndexHtmlTransformHook,
  type IndexHtmlTransformResult,
  type InferCustomEventPayload,
  type InlineConfig,
  type InternalResolveOptions,
  type InvalidatePayload,
  isCSSRequest,
  isFetchableDevEnvironment,
  isFileLoadingAllowed,
  isFileServingAllowed,
  isRunnableDevEnvironment,
  type JsonOptions,
  type KnownAsTypeMap,
  type LegacyOptions,
  type LessPreprocessorOptions,
  type LibraryFormats,
  type LibraryOptions,
  type LightningCSSOptions,
  loadConfigFromFile,
  loadEnv,
  type LogErrorOptions,
  type Logger,
  type LoggerOptions,
  type LogLevel,
  type LogOptions,
  type LogType,
  type Manifest,
  type ManifestChunk,
  type MapToFunction,
  type Matcher,
  mergeAlias,
  mergeConfig,
  minify,
  type MinifyOptions,
  type MinifyResult,
  type MinimalPluginContextWithoutEnvironment,
  type ModuleGraph,
  type ModuleNode,
  type ModulePreloadOptions,
  moduleRunnerTransform,
  type ModuleRunnerTransformOptions,
  type NormalizedHotChannel,
  type NormalizedHotChannelClient,
  type NormalizedServerHotChannel,
  normalizePath,
  type OptimizedDepInfo,
  optimizeDeps,
  type OxcOptions,
  parseAst,
  parseAstAsync,
  perEnvironmentPlugin,
  perEnvironmentState,
  type Plugin,
  type PluginContainer,
  type PluginHookUtils,
  type PluginOption,
  preprocessCSS,
  type PreprocessCSSResult,
  preview,
  type PreviewOptions,
  type PreviewServer,
  type PreviewServerHook,
  type ProxyOptions,
  type PrunePayload,
  type RenderBuiltAssetUrl,
  type ResolvedBuildEnvironmentOptions,
  type ResolvedBuildOptions,
  type ResolvedCSSOptions,
  type ResolvedDevEnvironmentOptions,
  type ResolvedModulePreloadOptions,
  type ResolvedPreviewOptions,
  type ResolvedServerOptions,
  type ResolvedServerUrls,
  type ResolvedSSROptions,
  type ResolvedUrl,
  type ResolvedWorkerOptions,
  resolveEnvPrefix,
  type ResolveFn,
  type ResolveModulePreloadDependenciesFn,
  type ResolveOptions,
  type ResolverFunction,
  type ResolverObject,
  type Rolldown,
  rolldownVersion,
  type Rollup,
  type RollupCommonJSOptions,
  type RollupDynamicImportVarsOptions,
  rollupVersion,
  type RunnableDevEnvironment,
  type RunnableDevEnvironmentContext,
  runnerImport,
  type SassPreprocessorOptions,
  searchForWorkspaceRoot,
  send,
  type SendOptions,
  type ServerHook,
  type ServerHotChannel,
  type ServerModuleRunnerOptions,
  type SkipInformation,
  sortUserPlugins,
  type SsrDepOptimizationConfig,
  type SSROptions,
  type SSRTarget,
  type StylusPreprocessorOptions,
  type Terser,
  type TerserOptions,
  type TransformOptions,
  type TransformResult,
  transformWithEsbuild,
  transformWithOxc,
  type Update,
  type UpdatePayload,
  type UserConfig,
  type UserConfigExport,
  type UserConfigFn,
  type UserConfigFnObject,
  type UserConfigFnPromise,
  version,
  type ViteBuilder,
  type ViteDevServer,
  type WatchOptions,
  type WebSocket,
  type WebSocketAlias,
  type WebSocketClient,
  type WebSocketCustomListener,
  type WebSocketServer,
  withFilter,
} from '@voidzero-dev/vite-plus/vite';
