import { resolveLocalVitePlus } from '../binding/index.js';
import cliPkg from '../package.json' with { type: 'json' };
import { renderCliDoc } from './utils/help.ts';
import { accent, log, printHeader } from './utils/terminal.ts';

/** Tool display names in the order shown by `vp --version`. */
const TOOL_DISPLAY_ORDER = [
  'vite',
  'rolldown',
  'vitest',
  'oxfmt',
  'oxlint',
  'oxlint-tsgolint',
  'tsdown',
] as const;

function getGlobalVersion(): string | null {
  return process.env.VP_GLOBAL_VERSION ?? null;
}

function getCliVersion(): string | null {
  return cliPkg.version ?? null;
}

/**
 * Resolve all tool versions from the locally installed vite-plus package.
 * Uses the `vite-plus/versions` export generated by `syncToolchainExports()`.
 */
async function resolveToolVersions(localPackagePath: string): Promise<Record<string, string>> {
  try {
    const mod = await import(`${localPackagePath}/dist/versions.js`);
    if (mod.versions && typeof mod.versions === 'object') {
      return mod.versions as Record<string, string>;
    }
  } catch {
    // versions module not available
  }
  return {};
}

/**
 * Print version information
 */
export async function printVersion(cwd: string) {
  const globalVersion = getGlobalVersion();
  const cliVersion = getCliVersion();
  const localMetadata = resolveLocalVitePlus(cwd);
  const localVersion = localMetadata?.version ?? null;
  const vpVersion = globalVersion ?? cliVersion ?? localVersion ?? 'unknown';

  printHeader();
  log(`vp v${vpVersion}\n`);

  const sections = [
    {
      title: 'Local vite-plus',
      rows: [
        {
          label: accent('vite-plus'),
          description: localVersion ? `v${localVersion}` : 'Not found',
        },
      ],
    },
  ];

  if (localMetadata) {
    const versions = await resolveToolVersions(localMetadata.path);

    sections.push({
      title: 'Tools',
      rows: TOOL_DISPLAY_ORDER.map((name) => ({
        label: accent(name),
        description: versions[name] ? `v${versions[name]}` : 'Not found',
      })),
    });
  }

  log(renderCliDoc({ sections }));
}

await printVersion(process.cwd());
