// Type declaration for dist/versions.js (generated by build.ts syncVersionsExport).
// The actual module is resolved at runtime from dist/global/ → dist/versions.js.
export declare const versions: {
  readonly vite: string;
  readonly rolldown: string;
  readonly tsdown: string;
  readonly vitest: string;
  readonly oxlint: string;
  readonly oxfmt: string;
  readonly 'oxlint-tsgolint': string;
};
