use ast_grep_config::{GlobalRules, RuleConfig, from_yaml_string};
use ast_grep_core::replacer::Replacer;
use ast_grep_language::{LanguageExt, SupportLang};
use serde_json::{Map, Value};
use vite_error::Error;

/// load script rules from yaml file
fn load_ast_grep_rules(yaml: &str) -> Result<Vec<RuleConfig<SupportLang>>, Error> {
    let globals = GlobalRules::default();
    let rules: Vec<RuleConfig<SupportLang>> = from_yaml_string::<SupportLang>(&yaml, &globals)?;
    Ok(rules)
}

/// rewrite a single script command string using rules
fn rewrite_script(script: &str, rules: &[RuleConfig<SupportLang>]) -> String {
    // current stores the current script text, and update it when the rule matches
    let mut current = script.to_string();

    for rule in rules {
        // only handle bash rules
        if rule.language != SupportLang::Bash {
            continue;
        }

        // parse current script with corresponding language
        let grep = rule.language.ast_grep(&current);
        let root = grep.root();

        // this matcher is the AST matcher generated by deserializing the YAML rule
        let matcher = &rule.matcher;

        // rules may not have fix (pure lint), skip here
        let fixers = match rule.get_fixer() {
            Ok(f) if !f.is_empty() => f,
            _ => continue,
        };

        // collect all matches and their replacements
        let mut replacements = Vec::new();
        for node in root.find_all(matcher) {
            let range = node.range();
            let replacement_bytes = fixers[0].generate_replacement(&node);
            let replacement_str = String::from_utf8_lossy(&replacement_bytes).to_string();
            replacements.push((range.start, range.end, replacement_str));
        }

        // Replace from back to front
        replacements.sort_by_key(|(start, _, _)| std::cmp::Reverse(*start));

        for (start, end, replacement) in replacements {
            current.replace_range(start..end, &replacement);
        }
    }

    current
}

/// rewrite scripts json content using rules from rules_yaml
pub fn rewrite_scripts(scripts_json: &str, rules_yaml: &str) -> Result<Option<String>, Error> {
    let mut scripts: Map<String, Value> = serde_json::from_str(scripts_json)?;
    let rules = load_ast_grep_rules(rules_yaml)?;

    let mut updated = false;
    // get scripts field (object)
    // let keys: Vec<String> = scripts.keys().cloned().collect();
    for value in scripts.values_mut() {
        if value.is_array() {
            // lint-staged scripts can be an array of strings
            // https://github.com/lint-staged/lint-staged?tab=readme-ov-file#packagejson-example
            if let Some(sub_scripts) = value.as_array_mut() {
                for sub_script in sub_scripts.iter_mut() {
                    if sub_script.is_string()
                        && let Some(raw_script) = sub_script.as_str()
                    {
                        let new_script = rewrite_script(raw_script, &rules);
                        if new_script != raw_script {
                            updated = true;
                            *sub_script = Value::String(new_script);
                        }
                    }
                }
            }
        } else if value.is_string() {
            if let Some(raw_script) = value.as_str() {
                let new_script = rewrite_script(raw_script, &rules);
                if new_script != raw_script {
                    updated = true;
                    *value = Value::String(new_script);
                }
            }
        }
    }

    if updated {
        let new_content = serde_json::to_string_pretty(&scripts)?;
        Ok(Some(new_content))
    } else {
        Ok(None)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const RULES_YAML: &str = r#"
# vite => vite dev
---
id: replace-vite-alone
language: bash
rule:
  kind: command
  has:
    kind: command_name
    regex: '^vite$'
  not:
    has:
      kind: word
      field: argument
fix: vite dev

# vite [OPTIONS] => vite dev [OPTIONS]
---
id: replace-vite-with-args
language: bash
severity: info
rule:
  pattern: vite $$$ARGS
  not:
    # ignore non-flag arguments
    regex: 'vite\s+[^-]'
fix: vite dev $$$ARGS

# oxlint => vite lint
---
id: replace-oxlint-alone
language: bash
rule:
  kind: command
  has:
    kind: command_name
    regex: '^oxlint$'
  not:
    has:
      kind: word
      field: argument
fix: vite lint

# oxlint [OPTIONS] => vite lint [OPTIONS]
---
id: replace-oxlint-with-args
language: bash
rule:
  pattern: oxlint $$$ARGS
fix: vite lint $$$ARGS
    "#;

    #[test]
    fn test_rewrite_script() {
        let globals = GlobalRules::default();
        let rules: Vec<RuleConfig<SupportLang>> =
            from_yaml_string::<SupportLang>(&RULES_YAML, &globals).unwrap();
        // vite commands
        assert_eq!(rewrite_script("vite", &rules), "vite dev");
        assert_eq!(rewrite_script("vite dev", &rules), "vite dev");
        assert_eq!(rewrite_script("vite i", &rules), "vite i");
        assert_eq!(rewrite_script("vite install", &rules), "vite install");
        assert_eq!(rewrite_script("vite test", &rules), "vite test");
        assert_eq!(rewrite_script("vite lint", &rules), "vite lint");
        assert_eq!(rewrite_script("vite fmt", &rules), "vite fmt");
        assert_eq!(rewrite_script("vite lib", &rules), "vite lib");
        assert_eq!(rewrite_script("vite preview", &rules), "vite preview");
        assert_eq!(rewrite_script("vite optimize", &rules), "vite optimize");
        assert_eq!(rewrite_script("vite build -r", &rules), "vite build -r");
        assert_eq!(rewrite_script("vite --port 3000", &rules), "vite dev --port 3000");
        assert_eq!(
            rewrite_script("vite --port 3000 --host 0.0.0.0 --open", &rules),
            "vite dev --port 3000 --host 0.0.0.0 --open"
        );
        assert_eq!(
            rewrite_script("vite --port 3000 || vite --port 3001", &rules),
            "vite dev --port 3000 || vite dev --port 3001"
        );
        assert_eq!(
            rewrite_script("npm run lint && vite --port 3000", &rules),
            "npm run lint && vite dev --port 3000"
        );
        assert_eq!(
            rewrite_script("vite --port 3000 && npm run lint", &rules),
            "vite dev --port 3000 && npm run lint"
        );
        assert_eq!(
            rewrite_script("vite && tsc --check && vite run -r build", &rules),
            "vite dev && tsc --check && vite run -r build"
        );
        assert_eq!(
            rewrite_script("vite && tsc --check && vite run test", &rules),
            "vite dev && tsc --check && vite run test"
        );
        assert_eq!(
            rewrite_script("vite && tsc --check && vite test", &rules),
            "vite dev && tsc --check && vite test"
        );
        assert_eq!(
            rewrite_script("prettier --write src/** vite", &rules),
            "prettier --write src/** vite"
        );
        // complex examples
        assert_eq!(
            rewrite_script("if [ -f file.txt ]; then vite; fi", &rules),
            "if [ -f file.txt ]; then vite dev; fi"
        );
        assert_eq!(
            rewrite_script("if [ -f file.txt ]; then vite --port 3000; fi", &rules),
            "if [ -f file.txt ]; then vite dev --port 3000; fi"
        );
        assert_eq!(
            rewrite_script("if [ -f file.txt ]; then vite --port 3000 && npm run lint; fi", &rules),
            "if [ -f file.txt ]; then vite dev --port 3000 && npm run lint; fi"
        );
        assert_eq!(
            rewrite_script(
                "if [ -f file.txt ]; then vite dev --port 3000 && npm run lint; fi",
                &rules
            ),
            "if [ -f file.txt ]; then vite dev --port 3000 && npm run lint; fi"
        );
        // oxlint commands
        assert_eq!(rewrite_script("oxlint", &rules), "vite lint");
        assert_eq!(rewrite_script("oxlint --type-aware", &rules), "vite lint --type-aware");
        assert_eq!(
            rewrite_script("oxlint --type-aware --config .oxlintrc", &rules),
            "vite lint --type-aware --config .oxlintrc"
        );
        assert_eq!(rewrite_script("oxlint && vite dev", &rules), "vite lint && vite dev");
        assert_eq!(
            rewrite_script("npm run type-check && oxlint --type-aware", &rules),
            "npm run type-check && vite lint --type-aware"
        );
    }

    #[test]
    fn test_rewrite_package_json_scripts_success() {
        let package_json_scripts = r#"
{
    "dev": "vite"
}
        "#;
        let updated = rewrite_scripts(package_json_scripts, &RULES_YAML)
            .expect("failed to rewrite package.json scripts");
        assert!(updated.is_some());
        assert_eq!(
            updated.unwrap(),
            r#"
{
  "dev": "vite dev"
}
        "#
            .trim()
        );
    }

    #[test]
    fn test_rewrite_package_json_scripts_lint_staged() {
        let package_json_scripts = r#"
        {
            "*.js": ["oxlint --fix --type-aware", "oxfmt --fix"],
            "*.ts": "oxfmt --fix"
        }
        "#;
        let updated = rewrite_scripts(package_json_scripts, &RULES_YAML)
            .expect("failed to rewrite package.json scripts");
        assert!(updated.is_some());
        assert_eq!(
            updated.unwrap(),
            r#"
{
  "*.js": [
    "vite lint --fix --type-aware",
    "oxfmt --fix"
  ],
  "*.ts": "oxfmt --fix"
}
        "#
            .trim()
        );
    }

    #[test]
    fn test_rewrite_package_json_scripts_no_update() {
        let package_json_scripts = r#"
        {
            "foo": "bar"
        }
        "#;
        let updated = rewrite_scripts(package_json_scripts, &RULES_YAML)
            .expect("failed to rewrite package.json scripts");
        assert!(updated.is_none());
    }
}
