name: Cargo Deny

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'Cargo.lock'
      - 'deny.toml'
      - '.github/workflows/deny.yml'
  push:
    branches:
      - main
    paths:
      - 'Cargo.lock'
      - 'deny.toml'
      - '.github/workflows/deny.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          submodules: true

      - uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.0
        with:
          restore-cache: false
          tools: cargo-deny

      - run: cargo deny check
