name: Release

on:
  workflow_dispatch:

permissions: {}

env:
  RELEASE_BUILD: 'true'
  DEBUG: 'napi:*'

jobs:
  build-rust:
    runs-on: ${{ matrix.settings.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        settings:
          - target: aarch64-apple-darwin
            os: namespace-profile-mac-default
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/clone
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      - uses: oxc-project/setup-rust@d286d43bc1f606abbd98096666ff8be68c8d5f57 # v1.0.2
        with:
          save-cache: ${{ github.ref_name == 'main' }}
          cache-key: release

      - name: Rustup Adds Target
        run: rustup target add ${{ matrix.settings.target }}

      - name: Add musl target (x86_64)
        if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
        run: rustup target add x86_64-unknown-linux-musl

      - name: Add musl target (aarch64)
        if: ${{ matrix.settings.target == 'aarch64-unknown-linux-gnu' }}
        run: rustup target add aarch64-unknown-linux-musl

      - uses: oxc-project/setup-node@fdbf0dfd334c4e6d56ceeb77d91c76339c2a0885 # v1.0.4

      - name: Set binding version
        run: |
          pnpm exec tool replace-file-content packages/cli/binding/Cargo.toml 'version = "0.0.0"' 'version = "0.0.0-${{ github.sha }}"'
          pnpm exec tool replace-file-content packages/global/binding/Cargo.toml 'version = "0.0.0"' 'version = "0.0.0-${{ github.sha }}"'

      - name: Configure Git for access to vite-task
        run: git config --global url."https://x-access-token:${{ secrets.VITE_TASK_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Build
        uses: ./.github/actions/build-upstream
        with:
          target: ${{ matrix.settings.target }}

      - name: Upload Vite+ native artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: vite-plus-native-${{ matrix.settings.target }}
          path: ./packages/cli/binding/*.node
          if-no-files-found: error

      - name: Upload Vite+ global binding artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: vite-plus-cli-native-${{ matrix.settings.target }}
          path: ./packages/global/binding/*.node
          if-no-files-found: error

      - name: Remove .node files before upload dist
        if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
        run: |
          rm ./packages/core/dist/**/*.node

      - name: Upload core dist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
        with:
          name: core
          path: ./packages/core/dist
          if-no-files-found: error

      - name: Upload cli dist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
        with:
          name: cli
          path: ./packages/cli/dist
          if-no-files-found: error

      - name: Upload global dist
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ matrix.settings.target == 'x86_64-unknown-linux-gnu' }}
        with:
          name: global
          path: ./packages/global/dist
          if-no-files-found: error

  Release:
    runs-on: ubuntu-latest
    needs: build-rust
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/clone

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Configure Git for access to vite-task
        run: git config --global url."https://x-access-token:${{ secrets.VITE_TASK_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"

      - name: Download cli dist
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/cli/dist
          pattern: cli
          merge-multiple: true

      - name: Download cli binding
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/cli/artifacts
          pattern: vite-plus-native-*

      - name: Download core dist
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/core/dist
          pattern: core
          merge-multiple: true

      - uses: ./.github/actions/download-rolldown-binaries
        with:
          github-token: ${{ github.token }}
          target: x86_64-unknown-linux-gnu
          upload: 'false'

      - name: Download global dist
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/global/dist
          pattern: global
          merge-multiple: true

      - name: Download global binding to dist
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/global/dist
          pattern: vite-plus-cli-native-*
          merge-multiple: true

      - name: Download global binding to artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: packages/global/artifacts
          pattern: vite-plus-cli-native-*

      - name: Set npm packages version
        run: |
          sed -i 's/"version": "0.0.0"/"version": "0.0.0-${{ github.sha }}"/' packages/core/package.json
          sed -i 's/"version": "0.0.0"/"version": "0.0.0-${{ github.sha }}"/' packages/test/package.json
          sed -i 's/"version": "0.0.0"/"version": "0.0.0-${{ github.sha }}"/' packages/cli/package.json
          sed -i 's/"version": "0.0.0"/"version": "0.0.0-${{ github.sha }}"/' packages/global/package.json

      - name: Build test
        run: pnpm --filter=@voidzero-dev/vite-plus-test build

      - name: 'Setup npm'
        run: |
          npm install -g npm@latest
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish native addons
        run: |
          node ./packages/cli/publish-native-addons.ts
          node ./packages/global/publish-native-addons.ts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          pnpm publish --filter=./packages/core --access public --no-git-checks
          pnpm publish --filter=./packages/test --access public --no-git-checks
          pnpm publish --filter=./packages/cli --access public --no-git-checks
          pnpm publish --filter=./packages/global --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
